In [3]:
import numpy as np

### Scalar Arithmatic

In [4]:
array = np.array([1,2,3])

In [9]:
print(array + 1)  # -> This adds "1" to every single elements in the array
print(array - 2)  # -> This subtracts "2" to every single elements in the array
print(array * 3)  # -> This multiplies "3" to every single elements in the array
print(array / 4)  # -> This divides by "4" to every single elements in the array

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]


### Verctorized math functions

In [10]:
print(np.sqrt(array))

[1.         1.41421356 1.73205081]


In [14]:
# Rounding off the numbers within the array:
array1 = np.array([1.01, 2.30, 4.98])
print(np.round(array1))

print(np.floor(array1))
print(np.ceil(array1))

[1. 2. 5.]
[1. 2. 4.]
[2. 3. 5.]


In [15]:
# Pi value
print(np.pi)

3.141592653589793


#### Excercise with vectorized math function

In [17]:
radii = np.array([1, 2, 3])

In [18]:
# Area of a circle
print(np.pi * radii ** 2) # -> pi * r^2

[ 3.14159265 12.56637061 28.27433388]


#### Element-wise arithmetic

In [20]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [23]:
print(array1 + array2)
print(array1[0] * array2[0])
print(array1[2] + array2[1])

[5 7 9]
4
8


#### Comparision Operator

In [25]:
print(array1 == array2)
print(array1 == 3)

[False False False]
[False False  True]


In [26]:
scores = np.array([91, 55, 100, 73, 82, 64])
scores [scores < 60] = 0
print(scores)

[ 91   0 100  73  82  64]
