In [2]:
import numpy as np

In [3]:
array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1], [2], [3], [4]])

In [6]:
print(array1.shape)
print(array2.shape)

(1, 4)
(4, 1)


In [7]:
print(array1 * array2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [10]:
array1 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

array2 = np.array([
    [1],
    [2],
    [3],
    [4]
])

In [11]:
print(array1 * array2)

ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 