In [2]:
import numpy as np

In [3]:
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [4]:
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## Row Selection

In [6]:
# first 3 rows after index '0'
print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
# from index 0 to last, skipping by step 2
print(array[::2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [9]:
# printing rows in reverse order:
print(array[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [10]:
# selecting every 2nd row in reverse:
print(array[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


## Column Selection

In [19]:
print(array[:,2])

[ 3  7 11 15]


In [20]:
# Negative value
print(array[:,-1]) # -> Prints last column

[ 4  8 12 16]


In [25]:
# Selecting first 3 columns
print(array[:,0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [26]:
# Skip first column only
print(array[:, 1:])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [27]:
# Selecting every second column
print(array[:,::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


### Combining row and column selections

In [28]:
print(array[0,0])

1


In [ ]:
# First two rows, first two columns:
print(array[0:2, 0:2])

[[1 2]
 [5 6]]


In [ ]:
# Last two rows, last two columns:
print(array[0:2, 2:4])

[[3 4]
 [7 8]]


In [42]:
# Last two rows, first two columns:
print(array[2:,:2])

[[ 9 10]
 [13 14]]


#### 